name: 'ci-nodejs-build-test'
description: 'Build and test action for nodejs CI'

inputs:
  working-dir:
    description: 'the project working directory'
    required: true

outputs:
  is_updated:
    description: 'informs if the update was done successfully or not'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'